### ISSUE TITLE
NotEmpty should be notBlank

### ISSUE THREAD

**Issue by MichaelHoughton** [steinkel/LogMail#2]
Hi There

In this file:

https://github.com/steinkel/LogMail/blob/master/Model/Logmail.php

Line 133

'id' => array('rule' => 'notEmpty'),

To work with new versions of CakePHP 2.x, this needs to be updated to:

'id' => array('rule' => 'notBlank'),

**Comment by steinkel** [comment]
Thank you, I've fixed the validation rule in tag 2.0.0
